### ISSUE TITLE
S’adapter à la nouvelle API GraphQL de meetup avant le 31/01/2022

### ISSUE THREAD

**Issue by dlecan** [BlockchainEtSociete/blockchainsociete.org#104]
Meetup coupe son API REST très bientôt, il faut passer au GraphQL

![F8118DF1-E499-4134-87CE-6114AFC677B2](https://user-images.githubusercontent.com/586631/149523383-9145b768-3499-4375-8090-5c9954581351.jpeg)

**Comment by Nigui** [comment]
Quel enfer cette API... 
Entre le manque de doc et la doc pas à jour.... 
Je m'essaye à graphql c'est peut être ça aussi
