### ISSUE TITLE
Revoir le SEO

### ISSUE THREAD

**Issue by Nigui** [BlockchainEtSociete/blockchainsociete.org#30]
Le site n'est pas référencé sur google "blockchain société nantes"

Ajouter des meta-data

**Comment by devsheder** [comment]
ça marche avec "blockchain société org" mais il faut avoir l'idée de tapé "org" ^^

**Comment by dlecan** [comment]
> Ajouter des meta-data
Il doit y avoir autre chose, ils ne sont quasiment plus utilisés par les moteurs
Ils veulent des choses visibles par les humaines :smile:

**Comment by dlecan** [comment]
Je m'en occupe

**Comment by devsheder** [comment]
@dlecan @Nigui le référencement Gogole s'est nettement améliorer grace à la mise en place d'Hugo :
![image](https://user-images.githubusercontent.com/19798549/58100260-93d96e80-7bdd-11e9-8a57-494c6c05a114.png)

On clot cette issu ?

**Comment by dlecan** [comment]
C'est bien meilleur sur Google
On doit pouvoir s'améliorer sur d'autres, comme Qwant.

A court terme, il reste le titre du site à améliorer, un peu court.

Un truc du genre :
- `Découvrir la Blockchain à Nantes | Blockchain et Société Association`
- `Blockchain et DLT à Nantes | Blockchain et Société Association`
- ...

**Comment by dlecan** [comment]
A revoir pour la v2 du site :
- [ ] Titre de toutes les pages
- [ ] Titre et description OpenGraph

**Comment by Nigui** [comment]
il y a actuellement un titre et toutes les info opengraph pour chaque page. Quel est le besoin ?

**Comment by dlecan** [comment]
Tout est nickel, exception faite du titre du site
`B&S`, c'est sympa visuellement, pas pas top pour le référencement

Il faudrait `Blockchain et Société` dans les balise `title` (et autres pour l'OG) et pourquoi pas `B&S` en titre visuel sur le site.

C'est possible ?

**Comment by Nigui** [comment]
Yes je vais faire ça

**Comment by Nigui** [comment]
fait dans le commit deefbe2
