### ISSUE TITLE
Ajouter la liste des meetups passés 

### ISSUE THREAD

**Issue by Nigui** [BlockchainEtSociete/blockchainsociete.org#35]
Comme discuté ensembles, il s'agit d'étendre l'issue #14 pour référencer TOUS les évènements passés.

Ils peuvent être sur la home sous la forme d'une liste horizontale scrollable, ou bien dans une page dédiée. 

Voici la requête sur l'API meetup pour récupérer tous les events : 
https://api.meetup.com/2/events?&sign=true&photo-host=public&group_urlname=Blockchain-Societe-Nantes&status=past,upcoming&page=100

**Comment by dlecan** [comment]
L'objectif, c'est le SEO : il faut donc que ce soit du contenu statique
Une petite moulette qui génère le HTML à partir de l'API ?

**Comment by devsheder** [comment]
On peut aussi faire simple :
 - lien dans la page web "Voir nos précédentes Meetup"
 - après clique sur le lien : appel API puis affichage d'une popin (responsive) sur la page

**Comment by devsheder** [comment]
Après (longue ^^) discussion avec @Nigui ok pour une moulinette qui génère l'HTML des deux sections :)

**Comment by devsheder** [comment]
Alors alors alors :

@Nigui création template HTML pour le carrousel des events

@devsheder création moulinette 
 - appel APIs Meetup (prochain Meetup + Meetups passés)
 - génération des fichiers HTML dans un dossier events : un fichier par event passé et un fichier "next_event.html"
 - génération du carrousel de la page principale (index.html) s'appuyant sur le template fourni par @Nigui 

Fonctionnement :
 - lancement du script de génération (en NodeJs 10 à priori)
 - push des fichiers sur une branche dédiée : acception sur master via PR
