### ISSUE TITLE
Page dédiée pour chaque évènement

### ISSUE THREAD

**Issue by Nigui** [BlockchainEtSociete/blockchainsociete.org#37]
Actuellement lors d'un clic sur `plus d'info` d'un évènement, sa page meetup s'affiche.
L'idée serait de générer avec `Hugo` une page d'évènement dédiée. Cela permet d'améliorer le référencement.

Dans cette page il y peut simplement y avoir dans un premier temps le titre et la description. 
Plus tard nous pourrons imaginer d'autres éléments (carte, commentaires,...)

**Comment by dlecan** [comment]
Géré par la nouvelle organisation des évènements ?

**Comment by Nigui** [comment]
non, il faudrait que le script de récupération des évènements génère une page markdown pour chaque évènement. C'est une amélioration possible

**Comment by dlecan** [comment]
On va faire ça
