### ISSUE TITLE
Dons en crypto et en fiat

### ISSUE THREAD

**Issue by Nigui** [BlockchainEtSociete/blockchainsociete.org#39]
Donner la possibilité aux utilisateurs de nous faire des dons en crypto monnaie. 

Il faut d'abord 
- demander l'avis aux membres de l'asso.
- décider de qui possède la clé privée des wallets. 
- généré un wallet pour chaque crypto qu'on décide d'accepter
- afficher l'adresse de chaque wallet sur le site.

**Comment by dlecan** [comment]
En fiat aussi, au travers de HelloAsso

**Comment by dlecan** [comment]
Peut-on commencer par les dons en fiat côté site web ? J'ai déjà le lien de don sur HelloAsso

**Comment by devsheder** [comment]
@Nigui : vu hier en réunion c'est ok pour les dons en crypto et en fiat
