### ISSUE TITLE
Carte évènement hauteur homogène

### ISSUE THREAD

**Issue by Nigui** [BlockchainEtSociete/blockchainsociete.org#41]
Faire en sorte que toutes les cartes de la section "évènements" aient la même hauteur.

**Comment by dlecan** [comment]
C'est toujours d'actualité ?

**Comment by Nigui** [comment]
Elles ne sont toujours pas de la même hauteur, donc oui. À faire un jour... peut être...

**Comment by Nigui** [comment]
réglé en v2
