### ISSUE TITLE
Automatiser la génération du site via Hugo

### ISSUE THREAD

**Issue by devsheder** [BlockchainEtSociete/blockchainsociete.org#43]
Utiliser une CI en ligne gratuite (type Travis) pour créer un pipeline qui fera les actions suivantes :
 * préparation environnement node `npm i`
 * lancement de la génération du site via Hugo `node .`
 * création d'une branche `git checkout -b generate_website_content`
 * commit Git `git commit -a -m "new website content"`
 * push sur GitHub `git push origin generate_website_content`
 * génération de la PR si possible, sinon cela sera fait manuellement sur GitHub

**Comment by devsheder** [comment]
@dlecan @Nigui 
J'ai paramétré un job sur Travis CI avec la conf suivante : https://github.com/devsheder/blockchainsociete.org/blob/master/.travis.yml et c'est ok 👍 

Par contre il faut mettre à jour le code js car la timezone de la VM Travis n'est pas la bonne du coup : https://github.com/devsheder/blockchainsociete.org/commit/3958ef8fc078d7efa97ab393eb404d7b53502d23

**Comment by devsheder** [comment]
Je ferai la doc plus tard

**Comment by dlecan** [comment]
Pas besoin de doc autre que dire d'aller voir le fichier .travis, lui-même bien documenté ;-)

Je propose qq améliorations sur le script de déploiement avant de le prendre en compte.
@devsheder il faudrait faire une PR avec ton code pour pouvoir commenter.

**Comment by devsheder** [comment]
Je vais pousser un PR, par contre il faut voir comment on peut avoir un compte commun Travis.
Pour l'instant c'est lieux à mon compte GitHub

**Comment by dlecan** [comment]
> par contre il faut voir comment on peut avoir un compte commun Travis.

Ca va se faire tout seul, dès que le build sera fait depuis ce dépôt et non pas depuis ton fork :-)

**Comment by dlecan** [comment]
Tout a été remplacé par Netlify
Build auto délenché en CRON par Github 3 fois par semaine
