### ISSUE TITLE
Ajouter la bannière de l'event sur les "cartes"

### ISSUE THREAD

**Issue by dlecan** [BlockchainEtSociete/blockchainsociete.org#45]
A partir du champ `photo_url` de la réponse de l'API meetup.

**Comment by Nigui** [comment]
![capture d ecran 2019-02-14 a 17 36 59](https://user-images.githubusercontent.com/6088236/52801901-26b6ba00-307f-11e9-8ea7-debc498f0ee7.png)

L'image est très petite ([source](https://secure.meetupstatic.com/photos/event/7/5/d/8/global_478470168.jpeg)).

Je ne sais pas ou tu la verrais ? J'ai un peu du mal à imaginer avec une image si petite.

**Comment by dlecan** [comment]
Ouais, pas terrible, il faudrait accéder à l'image en plus haute résolution.
Peut-être dans l'API des albums ?

Sinon je la mettrais bien où tu l'as mise
