### ISSUE TITLE
Mobile : barre d'adresse en noir

### ISSUE THREAD

**Issue by devsheder** [BlockchainEtSociete/blockchainsociete.org#51]
Sur les mobiles, on peut changer la couleur de la barre d'adresse du navigateur.
Comme la première section du site est en noire je pense que ça serait bien de mettre la barre d'adresse en noire aussi :)
Sur Chrome je sais que c'est `<meta name="theme-color" content="#ffffff">`

**Comment by dlecan** [comment]
Done j'ai l'impression
