### ISSUE TITLE
Retirer Google Analytics du site

### ISSUE THREAD

**Issue by Nigui** [BlockchainEtSociete/blockchainsociete.org#7]
Google Analytics est actuellement activé sur le site. 
Pour respecter la RGPD, il est indispensable d'en avertir le visiteur.

**Comment by devsheder** [comment]
Tu vois ça comment pour avertir chaque utilisateur de façon unique ?
 - popin ?
 - Cookie pour stocker ça ?

**Comment by dlecan** [comment]
Utiliser https://github.com/insites/cookieconsent/

Démo : https://cookieconsent.insites.com/app/themes/insites-cookie-consent/examples/example-4-opt-out.html

Et mettre en place avec les techniques décrites dans cet issue : https://github.com/insites/cookieconsent/issues/290

**Comment by dlecan** [comment]
Pas d'analytics, on peut s'en passer
On a rien à vendre

**Comment by Nigui** [comment]
plus de GA avec la v2 (c'est un plugin si jamais on souhaite l'ajouter)
