### ISSUE TITLE
v2 | La section "social" est un peu trop dense et les gens ne reconnaissent pas tous les logos

### ISSUE THREAD

**Issue by dlecan** [BlockchainEtSociete/blockchainsociete.org#79]
La section "social" est un peu trop dense et les gens ne reconnaissent pas tous les logos

https://v2--blockchainetsociete.netlify.app/#socials

~- [ ] Ajouter le lien vers le flux RSS~

Que faire pour améliorer ça ?

**Comment by dlecan** [comment]
Proposition n°1 : découper par action

Exemple :

- S'informer : Twitter, Facebook, LinkedIn, Youtube
- Participer : Meetup, Github
- Dialoguer : Slack, email

Evidemment, c'est un classement ambigu car Slack sert aussi à participer, mais ça serait plus clair je pense

**Comment by dlecan** [comment]
Proposition n°2 : cette liste bascule dans le footer

Et on refait une section plus toufue sur la page d'accueil qui explique chaque canal et ce qu'on peut y faire

**Comment by dlecan** [comment]
@BlockchainEtSociete/all un avis ?

**Comment by bpresles** [comment]
Proposition 1 pour ma part :)

**Comment by Nigui** [comment]
Pas certain que de classifier les outils soit nécessaire. On est sur des outils très populaires et avec des utilisations relativement spécifiques (on ne va pas demander des inscriptions à des évènements via slack ou twitter, et on ne va pas poster d'annonce sur Github ou Youtube). 
On peut cependant les remettre en forme et y ajouter le nom en dessous de chaque. On peut ajouter un petit "hint" en mode desktop pour chaque réseau si vraiment. 
du genre : 
![Screenshot 2022-01-06 at 15 50 13](https://user-images.githubusercontent.com/6088236/148401420-dfc7ac42-c97a-4628-857a-1897fa7df59b.png)

**Comment by Nigui** [comment]
@dlecan 
> [ ] Ajouter le lien vers le flux RSS

As tu le lien ?

**Comment by Nigui** [comment]
![Screenshot 2022-01-06 at 18 32 57](https://user-images.githubusercontent.com/6088236/148425536-6f41e6d5-cc91-4572-982e-70c51caa770e.png)
nouvelle proposition visible sur la branche v2

**Comment by dlecan** [comment]
> As tu le lien ?
Y'en a pas !

Je crée une autre US

**Comment by dlecan** [comment]
Cf. #91 pour traiter le sujet RSS

**Comment by dlecan** [comment]
La proposition de @Nigui  est une bonne évolution
On verra dans la durée s'il faut encore le travailler
