### ISSUE TITLE
Les ancres de la page d'accueil sont difficiles à découvrir

### ISSUE THREAD

**Issue by dlecan** [BlockchainEtSociete/blockchainsociete.org#80]
Toutes les sections de la page d'accueil ont un ancre : :heavy_check_mark: 
Mais il est difficile de découvrir le lien vers elle

https://v2--blockchainetsociete.netlify.app/

Exemple : https://v2--blockchainetsociete.netlify.app/#socials

Il faudrait un lien avec bouton sur chacune d'entre elles permettant :
- visualiser le lien de la section
- permettre de copier le lien

Reprendre le comportement de Github sur les sections markdown

**Comment by dlecan** [comment]
Peut-on avoir les ancres à droite des textes ?

**Comment by dlecan** [comment]
Nan, c'est très bien à gauche

**Comment by Nigui** [comment]
#84 les boutons ne copie pas l'url dans le presse-papier

**Comment by dlecan** [comment]
Clos par 86fe52e
