### ISSUE TITLE
v2 | Article de blog : améliorations à apporter avant publication (itération #1)

### ISSUE THREAD

**Issue by dlecan** [BlockchainEtSociete/blockchainsociete.org#81]
Exemple de billet de blog : https://v2--blockchainetsociete.netlify.app/full-example-blog-post/

Elements à discuter / améliorer (la plupart des éléments sont repris de la mise en forme d'un post Medium) :
- [x] ✅ Elargir la zone d'affichage du texte (`.prose: max-width` à passer de `65ch` à `76ch` ?)
- [x] ✅ Afficher la date (format FR) à côté de l'icone calendrier (ça a l'air d'être prévu pour. Si c'est cassé, pourquoi ?)
- [x] ✅ Ajouter l'auteur
- [x] ✅ Rajouter la légende pour le temps de lecture : `min` ?
- [x] ✅ Supprimer l'affichage le nombre de caractères
- [x] ✅ Lien hypertexte : supprimer le gras/over weighted
- [x] ✅ Puces : renforcer le contraste
- [x] ✅ Texte entre `backticks` : 
  - [x] ✅ Supprimer le renforcement du `weight`. Surligner comme `Github` le fait ?
  - [x] ✅ Ne pas afficher les backticks
- [x] ✅ OG : présente dans le code, mais le lien ne fonctionne pas apparemment (à tester sur https://cards-dev.twitter.com/validator)
 - [x] ✅ OG : prendre le lien de bannière s'il est présent dans le front-matter (las [conf Hugo](https://gohugo.io/templates/internal#configure-open-graph) présente plutôt l'usage de la propriété `images` plutôt que `thumbnail` présent dans l'exemple du thème - gérer les 2 ?)
 
:warning: attention à vérifier l'impact en mode dark

**Comment by Nigui** [comment]
test d'un morceau de code `hello world`

**Comment by Nigui** [comment]
il reste l'opengraph à gérer mais sinon les points terminés sont visibles depuis le commit [23f6008](https://github.com/BlockchainEtSociete/blockchainsociete.org/commit/23f6008424c322b13d9a3a619c7893604a42da37)

**Comment by dlecan** [comment]
@Nigui 
> Lien hypertexte : supprimer le gras/over weighted
Ce n'est pas encore déployé, je vois tj une différence sous FFX ? J'ai décoché du coup

**Comment by dlecan** [comment]
J'ai validé tout ce qui a été coché : :muscle: :clap:

**Comment by Nigui** [comment]
@dlecan  je te propose de corriger le problème de lien en "gras" car je ne le constate ni sur firefox ni sur brave

**Comment by dlecan** [comment]
Ca vient de `.prose a` qui a `font-weight: 500;`

D'où vient le style `prose` ? je sèche un peu pour le moment :sweat_smile:

**Comment by dlecan** [comment]
En mode dev, on a ça dans le fichier `style.css` :

```
.prose a {
  color: inherit;
  text-decoration: underline;
  font-weight: 500;
}
```

De quel import cela vient ? Mystère

**Comment by dlecan** [comment]
Ca y est, j'ai trouvé @Nigui : ça vient de https://tailwindcss.com/docs/typography-plugin, valeur par défaut
Il va me falloir un peu de temps pour comprendre comment Tailwind fonctionne pour faire la modif

Tu ne peux pas t'y (re)coller ?

Merci

**Comment by dlecan** [comment]
@Nigui Ajout d'un complément de spec sur l'OG

**Comment by Nigui** [comment]
voilà, j'ai viré le fontWeight, mais je ne peux pas vérifier visuellement le résultat.

**Comment by Nigui** [comment]
Pour l'opengraph il faut simplement utiliser la propriété "images" dans front-matter 
cf https://gohugo.io/templates/internal/#configure-open-graph

**Comment by dlecan** [comment]
> Pour l'opengraph il faut simplement utiliser la propriété "images" dans front-matter
Pas très DRY tout ça
Bon, ça fait le job

**Comment by dlecan** [comment]
Tout est validé, déjà déployé

**Comment by Nigui** [comment]
> Pas très DRY tout ça Bon, ça fait le job
Il semble y avoir une méthode si tu veux vraiment être "dry" c'est de n'utiliser que la propriété `thumbnail` mais par contre importer une image dans le repo avec comme nom `*thumbnail*`, le plugin opengraph semble fonctionner comme ça quand il n'y a pas la propriété `images`. 
Mais bon... c'est pas non plus catastrophique d'avoir les deux
