### ISSUE TITLE
v2 | Les liens ne sont pas visibles sur la page d'accueil

### ISSUE THREAD

**Issue by dlecan** [BlockchainEtSociete/blockchainsociete.org#92]
J'ai ajouté un lien sur la page d'accueil de la v2 dans la section "Team" (lien sur `1200 membres sur Meetup`).
Le lien est fonctionnel, mais n'a aucune décoration, donc on ne le voit pas.

**Comment by dlecan** [comment]
cc @Nigui

**Comment by Nigui** [comment]
ce n'est pas un bug mais une feature 🤪 
Tailwind a désactivé la décoration des liens par défaut...
Je remet du coup. Donc tous les liens seront sous-lignés par défaut et il faudra à la main désactiver si besoin

**Comment by Nigui** [comment]
finalement, vu comment est codée le template, il serait plus judicieux de conserver cette logique (no-underline first), sinon on va avoir beaucoup d'endroit ou il faudra ajouter "no-underline" (e.g menu, header, cartes cliquables,...).
En sachant que cette logique est inversée quand on écrit des articles.
@dlecan un avis?

**Comment by dlecan** [comment]
J'ai compris l'esprit

J'ai ajouté la classe `prose` au bon div

**Comment by dlecan** [comment]
Fixé par #d7bae26 sur la v2
