### ISSUE TITLE
Bugs graphiques

### ISSUE THREAD

**Issue by ftreguer** [BlockchainEtSociete/blockchainsociete.org#97]
les metadatas d'un post de blog ne s'affiches pas bien.

Il manque un espace entre les cartes d'events et le lien pour accéder à la liste complète des events

**Comment by Nigui** [comment]
le second point a été corrigé dans le commit https://github.com/BlockchainEtSociete/blockchainsociete.org/commit/1e98bbdbdc269c072f9f2b99048626eb08c604d3
